server:
  port: 8081

application:
  openAi:
    apiKey: yout-open-ai-api-key
    completionUrl: https://api.openai.com/v1/chat/completions
    maxRetryCall: 3
    stopChatWord: Yahia
    model: gpt-3.5-turbo-1106
    temperature: 1
    n: 1

  googleGemini:
    projectId: your-google-cloud-project-id
    location: us-central1
    modelName: gemini-pro-vision
    stopChatWord: Yahia


